"use strict";
//write a series of conditional test .Predict the the the result of each test 
Object.defineProperty(exports, "__esModule", { value: true });
let car = 'subaru';
console.log("Is car == 'subaru' ? I predict True .");
console.log(car == 'subaru');
console.log("Is car == 'Toyoto'? I predict False.");
console.log(car == 'Toyoto');
let Iam = 'Good student';
console.log("Is iam == Good student ? I predict True.");
console.log(Iam == 'Good student');
console.log("Is iam == 'Bad student' ? I predict False.");
console.log(Iam == 'Bad student');
let hobby = 'Reading';
console.log("Is hobby =='Reading' ? I predict True.");
console.log(hobby == "Reading");
console.log("Is hobby =='Writing' ? I predict False.");
console.log(hobby == "Writing");
let city = 'Karachi';
console.log("Is city == 'Karachi'? I predict True");
console.log(city == "Karachi");
console.log("Is city == 'Lahore '? I predict False.");
console.log(city == " Lahore");
let color = 'white';
console.log("Is color == white ? I predict True.");
console.log(color == 'white');
console.log("Is color == Black  ? I predict False .");
console.log(color == 'Black');
