"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let a = 3;
let b = 5;
let c = 10;
let d = 2;
let e = 16;
let f = 4;
console.log('addition of 3 + 5 =', a + b);
console.log('subtraction of 10 - 2= ', c - d);
console.log('division of 16 / 2 =', e / d);
console.log('muliply of 4 * 2 =', f * d);
